Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64" # Ubuntu 20.04 box
  config.vm.network "private_network", ip: "192.168.56.66" # Private network with DHCP

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048" # Set memory size to 1GB
    vb.cpus = 2 # Set number of CPUs to 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Update the system and install necessary packages
    sudo apt update
    sudo apt install openjdk-11-jdk -y
    sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
    https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null
    sudo apt-get update
    sudo apt-get install jenkins -y
  SHELL
end
